/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as AppYearInReviewRouteImport } from './routes/app.year-in-review'
import { Route as AppWalletRouteImport } from './routes/app.wallet'
import { Route as AppVendorsRouteImport } from './routes/app.vendors'
import { Route as AppStoryComposerRouteImport } from './routes/app.story-composer'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReferralRouteImport } from './routes/app.referral'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPremiumRouteImport } from './routes/app.premium'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppInspirationsRouteImport } from './routes/app.inspirations'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppGiftIdeasRouteImport } from './routes/app.gift-ideas'
import { Route as AppFavoritesRouteImport } from './routes/app.favorites'
import { Route as AppExploreRouteImport } from './routes/app.explore'
import { Route as AppCreateRouteImport } from './routes/app.create'
import { Route as AppCommunityRouteImport } from './routes/app.community'
import { Route as AppCareRouteImport } from './routes/app.care'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'
import { Route as EventsSlugWeatherRouteImport } from './routes/events.$slug.weather'
import { Route as EventsSlugToastRouteImport } from './routes/events.$slug.toast'
import { Route as EventsSlugTimelineRouteImport } from './routes/events.$slug.timeline'
import { Route as EventsSlugThanksRouteImport } from './routes/events.$slug.thanks'
import { Route as EventsSlugSpeechesRouteImport } from './routes/events.$slug.speeches'
import { Route as EventsSlugSouvenirRouteImport } from './routes/events.$slug.souvenir'
import { Route as EventsSlugSeatingRouteImport } from './routes/events.$slug.seating'
import { Route as EventsSlugRsvpRouteImport } from './routes/events.$slug.rsvp'
import { Route as EventsSlugReplayRouteImport } from './routes/events.$slug.replay'
import { Route as EventsSlugRegistryRouteImport } from './routes/events.$slug.registry'
import { Route as EventsSlugPollsRouteImport } from './routes/events.$slug.polls'
import { Route as EventsSlugPlaylistRouteImport } from './routes/events.$slug.playlist'
import { Route as EventsSlugPhotoboothRouteImport } from './routes/events.$slug.photobooth'
import { Route as EventsSlugModerationRouteImport } from './routes/events.$slug.moderation'
import { Route as EventsSlugMapRouteImport } from './routes/events.$slug.map'
import { Route as EventsSlugLiveAnalyticsRouteImport } from './routes/events.$slug.live-analytics'
import { Route as EventsSlugLiveRouteImport } from './routes/events.$slug.live'
import { Route as EventsSlugKidsRouteImport } from './routes/events.$slug.kids'
import { Route as EventsSlugInviteRouteImport } from './routes/events.$slug.invite'
import { Route as EventsSlugGuestsRouteImport } from './routes/events.$slug.guests'
import { Route as EventsSlugGuestbookRouteImport } from './routes/events.$slug.guestbook'
import { Route as EventsSlugGiftsReceivedRouteImport } from './routes/events.$slug.gifts-received'
import { Route as EventsSlugFaqRouteImport } from './routes/events.$slug.faq'
import { Route as EventsSlugEditRouteImport } from './routes/events.$slug.edit'
import { Route as EventsSlugDresscodeRouteImport } from './routes/events.$slug.dresscode'
import { Route as EventsSlugDisplayRouteImport } from './routes/events.$slug.display'
import { Route as EventsSlugDashboardRouteImport } from './routes/events.$slug.dashboard'
import { Route as EventsSlugCountdownRouteImport } from './routes/events.$slug.countdown'
import { Route as EventsSlugContributorsRouteImport } from './routes/events.$slug.contributors'
import { Route as EventsSlugChecklistRouteImport } from './routes/events.$slug.checklist'
import { Route as EventsSlugCheckinRouteImport } from './routes/events.$slug.checkin'
import { Route as EventsSlugCarpoolRouteImport } from './routes/events.$slug.carpool'
import { Route as EventsSlugCamerasRouteImport } from './routes/events.$slug.cameras'
import { Route as EventsSlugBudgetRouteImport } from './routes/events.$slug.budget'
import { Route as EventsSlugAlbumRouteImport } from './routes/events.$slug.album'
import { Route as EventsSlugActivityRouteImport } from './routes/events.$slug.activity'
import { Route as AppVendorsIdRouteImport } from './routes/app.vendors.$id'
import { Route as AppUsersIdRouteImport } from './routes/app.users.$id'
import { Route as AppPostsIdRouteImport } from './routes/app.posts.$id'
import { Route as AppMessagesIdRouteImport } from './routes/app.messages.$id'
import { Route as EventsSlugLiveSetupRouteImport } from './routes/events.$slug.live.setup'
import { Route as EventsSlugGuestbookNewRouteImport } from './routes/events.$slug.guestbook.new'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/stories/$slug',
  path: '/stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppYearInReviewRoute = AppYearInReviewRouteImport.update({
  id: '/year-in-review',
  path: '/year-in-review',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppStoryComposerRoute = AppStoryComposerRouteImport.update({
  id: '/story-composer',
  path: '/story-composer',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralRoute = AppReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiumRoute = AppPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppInspirationsRoute = AppInspirationsRouteImport.update({
  id: '/inspirations',
  path: '/inspirations',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppGiftIdeasRoute = AppGiftIdeasRouteImport.update({
  id: '/gift-ideas',
  path: '/gift-ideas',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppCareRoute = AppCareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const EventsSlugWeatherRoute = EventsSlugWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugToastRoute = EventsSlugToastRouteImport.update({
  id: '/toast',
  path: '/toast',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugTimelineRoute = EventsSlugTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugThanksRoute = EventsSlugThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugSpeechesRoute = EventsSlugSpeechesRouteImport.update({
  id: '/speeches',
  path: '/speeches',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugSouvenirRoute = EventsSlugSouvenirRouteImport.update({
  id: '/souvenir',
  path: '/souvenir',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugSeatingRoute = EventsSlugSeatingRouteImport.update({
  id: '/seating',
  path: '/seating',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugRsvpRoute = EventsSlugRsvpRouteImport.update({
  id: '/rsvp',
  path: '/rsvp',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugReplayRoute = EventsSlugReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugRegistryRoute = EventsSlugRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugPollsRoute = EventsSlugPollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugPlaylistRoute = EventsSlugPlaylistRouteImport.update({
  id: '/playlist',
  path: '/playlist',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugPhotoboothRoute = EventsSlugPhotoboothRouteImport.update({
  id: '/photobooth',
  path: '/photobooth',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugModerationRoute = EventsSlugModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugMapRoute = EventsSlugMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugLiveAnalyticsRoute = EventsSlugLiveAnalyticsRouteImport.update({
  id: '/live-analytics',
  path: '/live-analytics',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugLiveRoute = EventsSlugLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugKidsRoute = EventsSlugKidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugInviteRoute = EventsSlugInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugGuestsRoute = EventsSlugGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugGuestbookRoute = EventsSlugGuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugGiftsReceivedRoute = EventsSlugGiftsReceivedRouteImport.update({
  id: '/gifts-received',
  path: '/gifts-received',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugFaqRoute = EventsSlugFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugEditRoute = EventsSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugDresscodeRoute = EventsSlugDresscodeRouteImport.update({
  id: '/dresscode',
  path: '/dresscode',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugDisplayRoute = EventsSlugDisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugDashboardRoute = EventsSlugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugCountdownRoute = EventsSlugCountdownRouteImport.update({
  id: '/countdown',
  path: '/countdown',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugContributorsRoute = EventsSlugContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugChecklistRoute = EventsSlugChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugCheckinRoute = EventsSlugCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugCarpoolRoute = EventsSlugCarpoolRouteImport.update({
  id: '/carpool',
  path: '/carpool',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugCamerasRoute = EventsSlugCamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugBudgetRoute = EventsSlugBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugAlbumRoute = EventsSlugAlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugActivityRoute = EventsSlugActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => EventsSlugRoute,
} as any)
const AppVendorsIdRoute = AppVendorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppVendorsRoute,
} as any)
const AppUsersIdRoute = AppUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsIdRoute = AppPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIdRoute = AppMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMessagesRoute,
} as any)
const EventsSlugLiveSetupRoute = EventsSlugLiveSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => EventsSlugLiveRoute,
} as any)
const EventsSlugGuestbookNewRoute = EventsSlugGuestbookNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EventsSlugGuestbookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/legal': typeof LegalRoute
  '/onboarding': typeof OnboardingRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/care': typeof AppCareRoute
  '/app/community': typeof AppCommunityRoute
  '/app/create': typeof AppCreateRoute
  '/app/explore': typeof AppExploreRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/gift-ideas': typeof AppGiftIdeasRoute
  '/app/help': typeof AppHelpRoute
  '/app/inspirations': typeof AppInspirationsRoute
  '/app/messages': typeof AppMessagesRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referral': typeof AppReferralRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/story-composer': typeof AppStoryComposerRoute
  '/app/vendors': typeof AppVendorsRouteWithChildren
  '/app/wallet': typeof AppWalletRoute
  '/app/year-in-review': typeof AppYearInReviewRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/stories/$slug': typeof StoriesSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/messages/$id': typeof AppMessagesIdRoute
  '/app/posts/$id': typeof AppPostsIdRoute
  '/app/users/$id': typeof AppUsersIdRoute
  '/app/vendors/$id': typeof AppVendorsIdRoute
  '/events/$slug/activity': typeof EventsSlugActivityRoute
  '/events/$slug/album': typeof EventsSlugAlbumRoute
  '/events/$slug/budget': typeof EventsSlugBudgetRoute
  '/events/$slug/cameras': typeof EventsSlugCamerasRoute
  '/events/$slug/carpool': typeof EventsSlugCarpoolRoute
  '/events/$slug/checkin': typeof EventsSlugCheckinRoute
  '/events/$slug/checklist': typeof EventsSlugChecklistRoute
  '/events/$slug/contributors': typeof EventsSlugContributorsRoute
  '/events/$slug/countdown': typeof EventsSlugCountdownRoute
  '/events/$slug/dashboard': typeof EventsSlugDashboardRoute
  '/events/$slug/display': typeof EventsSlugDisplayRoute
  '/events/$slug/dresscode': typeof EventsSlugDresscodeRoute
  '/events/$slug/edit': typeof EventsSlugEditRoute
  '/events/$slug/faq': typeof EventsSlugFaqRoute
  '/events/$slug/gifts-received': typeof EventsSlugGiftsReceivedRoute
  '/events/$slug/guestbook': typeof EventsSlugGuestbookRouteWithChildren
  '/events/$slug/guests': typeof EventsSlugGuestsRoute
  '/events/$slug/invite': typeof EventsSlugInviteRoute
  '/events/$slug/kids': typeof EventsSlugKidsRoute
  '/events/$slug/live': typeof EventsSlugLiveRouteWithChildren
  '/events/$slug/live-analytics': typeof EventsSlugLiveAnalyticsRoute
  '/events/$slug/map': typeof EventsSlugMapRoute
  '/events/$slug/moderation': typeof EventsSlugModerationRoute
  '/events/$slug/photobooth': typeof EventsSlugPhotoboothRoute
  '/events/$slug/playlist': typeof EventsSlugPlaylistRoute
  '/events/$slug/polls': typeof EventsSlugPollsRoute
  '/events/$slug/registry': typeof EventsSlugRegistryRoute
  '/events/$slug/replay': typeof EventsSlugReplayRoute
  '/events/$slug/rsvp': typeof EventsSlugRsvpRoute
  '/events/$slug/seating': typeof EventsSlugSeatingRoute
  '/events/$slug/souvenir': typeof EventsSlugSouvenirRoute
  '/events/$slug/speeches': typeof EventsSlugSpeechesRoute
  '/events/$slug/thanks': typeof EventsSlugThanksRoute
  '/events/$slug/timeline': typeof EventsSlugTimelineRoute
  '/events/$slug/toast': typeof EventsSlugToastRoute
  '/events/$slug/weather': typeof EventsSlugWeatherRoute
  '/events/$slug/guestbook/new': typeof EventsSlugGuestbookNewRoute
  '/events/$slug/live/setup': typeof EventsSlugLiveSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/legal': typeof LegalRoute
  '/onboarding': typeof OnboardingRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/care': typeof AppCareRoute
  '/app/community': typeof AppCommunityRoute
  '/app/create': typeof AppCreateRoute
  '/app/explore': typeof AppExploreRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/gift-ideas': typeof AppGiftIdeasRoute
  '/app/help': typeof AppHelpRoute
  '/app/inspirations': typeof AppInspirationsRoute
  '/app/messages': typeof AppMessagesRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referral': typeof AppReferralRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/story-composer': typeof AppStoryComposerRoute
  '/app/vendors': typeof AppVendorsRouteWithChildren
  '/app/wallet': typeof AppWalletRoute
  '/app/year-in-review': typeof AppYearInReviewRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/stories/$slug': typeof StoriesSlugRoute
  '/app': typeof AppIndexRoute
  '/app/messages/$id': typeof AppMessagesIdRoute
  '/app/posts/$id': typeof AppPostsIdRoute
  '/app/users/$id': typeof AppUsersIdRoute
  '/app/vendors/$id': typeof AppVendorsIdRoute
  '/events/$slug/activity': typeof EventsSlugActivityRoute
  '/events/$slug/album': typeof EventsSlugAlbumRoute
  '/events/$slug/budget': typeof EventsSlugBudgetRoute
  '/events/$slug/cameras': typeof EventsSlugCamerasRoute
  '/events/$slug/carpool': typeof EventsSlugCarpoolRoute
  '/events/$slug/checkin': typeof EventsSlugCheckinRoute
  '/events/$slug/checklist': typeof EventsSlugChecklistRoute
  '/events/$slug/contributors': typeof EventsSlugContributorsRoute
  '/events/$slug/countdown': typeof EventsSlugCountdownRoute
  '/events/$slug/dashboard': typeof EventsSlugDashboardRoute
  '/events/$slug/display': typeof EventsSlugDisplayRoute
  '/events/$slug/dresscode': typeof EventsSlugDresscodeRoute
  '/events/$slug/edit': typeof EventsSlugEditRoute
  '/events/$slug/faq': typeof EventsSlugFaqRoute
  '/events/$slug/gifts-received': typeof EventsSlugGiftsReceivedRoute
  '/events/$slug/guestbook': typeof EventsSlugGuestbookRouteWithChildren
  '/events/$slug/guests': typeof EventsSlugGuestsRoute
  '/events/$slug/invite': typeof EventsSlugInviteRoute
  '/events/$slug/kids': typeof EventsSlugKidsRoute
  '/events/$slug/live': typeof EventsSlugLiveRouteWithChildren
  '/events/$slug/live-analytics': typeof EventsSlugLiveAnalyticsRoute
  '/events/$slug/map': typeof EventsSlugMapRoute
  '/events/$slug/moderation': typeof EventsSlugModerationRoute
  '/events/$slug/photobooth': typeof EventsSlugPhotoboothRoute
  '/events/$slug/playlist': typeof EventsSlugPlaylistRoute
  '/events/$slug/polls': typeof EventsSlugPollsRoute
  '/events/$slug/registry': typeof EventsSlugRegistryRoute
  '/events/$slug/replay': typeof EventsSlugReplayRoute
  '/events/$slug/rsvp': typeof EventsSlugRsvpRoute
  '/events/$slug/seating': typeof EventsSlugSeatingRoute
  '/events/$slug/souvenir': typeof EventsSlugSouvenirRoute
  '/events/$slug/speeches': typeof EventsSlugSpeechesRoute
  '/events/$slug/thanks': typeof EventsSlugThanksRoute
  '/events/$slug/timeline': typeof EventsSlugTimelineRoute
  '/events/$slug/toast': typeof EventsSlugToastRoute
  '/events/$slug/weather': typeof EventsSlugWeatherRoute
  '/events/$slug/guestbook/new': typeof EventsSlugGuestbookNewRoute
  '/events/$slug/live/setup': typeof EventsSlugLiveSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/legal': typeof LegalRoute
  '/onboarding': typeof OnboardingRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/care': typeof AppCareRoute
  '/app/community': typeof AppCommunityRoute
  '/app/create': typeof AppCreateRoute
  '/app/explore': typeof AppExploreRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/gift-ideas': typeof AppGiftIdeasRoute
  '/app/help': typeof AppHelpRoute
  '/app/inspirations': typeof AppInspirationsRoute
  '/app/messages': typeof AppMessagesRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referral': typeof AppReferralRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/story-composer': typeof AppStoryComposerRoute
  '/app/vendors': typeof AppVendorsRouteWithChildren
  '/app/wallet': typeof AppWalletRoute
  '/app/year-in-review': typeof AppYearInReviewRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/stories/$slug': typeof StoriesSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/messages/$id': typeof AppMessagesIdRoute
  '/app/posts/$id': typeof AppPostsIdRoute
  '/app/users/$id': typeof AppUsersIdRoute
  '/app/vendors/$id': typeof AppVendorsIdRoute
  '/events/$slug/activity': typeof EventsSlugActivityRoute
  '/events/$slug/album': typeof EventsSlugAlbumRoute
  '/events/$slug/budget': typeof EventsSlugBudgetRoute
  '/events/$slug/cameras': typeof EventsSlugCamerasRoute
  '/events/$slug/carpool': typeof EventsSlugCarpoolRoute
  '/events/$slug/checkin': typeof EventsSlugCheckinRoute
  '/events/$slug/checklist': typeof EventsSlugChecklistRoute
  '/events/$slug/contributors': typeof EventsSlugContributorsRoute
  '/events/$slug/countdown': typeof EventsSlugCountdownRoute
  '/events/$slug/dashboard': typeof EventsSlugDashboardRoute
  '/events/$slug/display': typeof EventsSlugDisplayRoute
  '/events/$slug/dresscode': typeof EventsSlugDresscodeRoute
  '/events/$slug/edit': typeof EventsSlugEditRoute
  '/events/$slug/faq': typeof EventsSlugFaqRoute
  '/events/$slug/gifts-received': typeof EventsSlugGiftsReceivedRoute
  '/events/$slug/guestbook': typeof EventsSlugGuestbookRouteWithChildren
  '/events/$slug/guests': typeof EventsSlugGuestsRoute
  '/events/$slug/invite': typeof EventsSlugInviteRoute
  '/events/$slug/kids': typeof EventsSlugKidsRoute
  '/events/$slug/live': typeof EventsSlugLiveRouteWithChildren
  '/events/$slug/live-analytics': typeof EventsSlugLiveAnalyticsRoute
  '/events/$slug/map': typeof EventsSlugMapRoute
  '/events/$slug/moderation': typeof EventsSlugModerationRoute
  '/events/$slug/photobooth': typeof EventsSlugPhotoboothRoute
  '/events/$slug/playlist': typeof EventsSlugPlaylistRoute
  '/events/$slug/polls': typeof EventsSlugPollsRoute
  '/events/$slug/registry': typeof EventsSlugRegistryRoute
  '/events/$slug/replay': typeof EventsSlugReplayRoute
  '/events/$slug/rsvp': typeof EventsSlugRsvpRoute
  '/events/$slug/seating': typeof EventsSlugSeatingRoute
  '/events/$slug/souvenir': typeof EventsSlugSouvenirRoute
  '/events/$slug/speeches': typeof EventsSlugSpeechesRoute
  '/events/$slug/thanks': typeof EventsSlugThanksRoute
  '/events/$slug/timeline': typeof EventsSlugTimelineRoute
  '/events/$slug/toast': typeof EventsSlugToastRoute
  '/events/$slug/weather': typeof EventsSlugWeatherRoute
  '/events/$slug/guestbook/new': typeof EventsSlugGuestbookNewRoute
  '/events/$slug/live/setup': typeof EventsSlugLiveSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/join'
    | '/legal'
    | '/onboarding'
    | '/app/achievements'
    | '/app/agenda'
    | '/app/care'
    | '/app/community'
    | '/app/create'
    | '/app/explore'
    | '/app/favorites'
    | '/app/gift-ideas'
    | '/app/help'
    | '/app/inspirations'
    | '/app/messages'
    | '/app/notifications'
    | '/app/premium'
    | '/app/profile'
    | '/app/referral'
    | '/app/settings'
    | '/app/story-composer'
    | '/app/vendors'
    | '/app/wallet'
    | '/app/year-in-review'
    | '/events/$slug'
    | '/stories/$slug'
    | '/app/'
    | '/app/messages/$id'
    | '/app/posts/$id'
    | '/app/users/$id'
    | '/app/vendors/$id'
    | '/events/$slug/activity'
    | '/events/$slug/album'
    | '/events/$slug/budget'
    | '/events/$slug/cameras'
    | '/events/$slug/carpool'
    | '/events/$slug/checkin'
    | '/events/$slug/checklist'
    | '/events/$slug/contributors'
    | '/events/$slug/countdown'
    | '/events/$slug/dashboard'
    | '/events/$slug/display'
    | '/events/$slug/dresscode'
    | '/events/$slug/edit'
    | '/events/$slug/faq'
    | '/events/$slug/gifts-received'
    | '/events/$slug/guestbook'
    | '/events/$slug/guests'
    | '/events/$slug/invite'
    | '/events/$slug/kids'
    | '/events/$slug/live'
    | '/events/$slug/live-analytics'
    | '/events/$slug/map'
    | '/events/$slug/moderation'
    | '/events/$slug/photobooth'
    | '/events/$slug/playlist'
    | '/events/$slug/polls'
    | '/events/$slug/registry'
    | '/events/$slug/replay'
    | '/events/$slug/rsvp'
    | '/events/$slug/seating'
    | '/events/$slug/souvenir'
    | '/events/$slug/speeches'
    | '/events/$slug/thanks'
    | '/events/$slug/timeline'
    | '/events/$slug/toast'
    | '/events/$slug/weather'
    | '/events/$slug/guestbook/new'
    | '/events/$slug/live/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/join'
    | '/legal'
    | '/onboarding'
    | '/app/achievements'
    | '/app/agenda'
    | '/app/care'
    | '/app/community'
    | '/app/create'
    | '/app/explore'
    | '/app/favorites'
    | '/app/gift-ideas'
    | '/app/help'
    | '/app/inspirations'
    | '/app/messages'
    | '/app/notifications'
    | '/app/premium'
    | '/app/profile'
    | '/app/referral'
    | '/app/settings'
    | '/app/story-composer'
    | '/app/vendors'
    | '/app/wallet'
    | '/app/year-in-review'
    | '/events/$slug'
    | '/stories/$slug'
    | '/app'
    | '/app/messages/$id'
    | '/app/posts/$id'
    | '/app/users/$id'
    | '/app/vendors/$id'
    | '/events/$slug/activity'
    | '/events/$slug/album'
    | '/events/$slug/budget'
    | '/events/$slug/cameras'
    | '/events/$slug/carpool'
    | '/events/$slug/checkin'
    | '/events/$slug/checklist'
    | '/events/$slug/contributors'
    | '/events/$slug/countdown'
    | '/events/$slug/dashboard'
    | '/events/$slug/display'
    | '/events/$slug/dresscode'
    | '/events/$slug/edit'
    | '/events/$slug/faq'
    | '/events/$slug/gifts-received'
    | '/events/$slug/guestbook'
    | '/events/$slug/guests'
    | '/events/$slug/invite'
    | '/events/$slug/kids'
    | '/events/$slug/live'
    | '/events/$slug/live-analytics'
    | '/events/$slug/map'
    | '/events/$slug/moderation'
    | '/events/$slug/photobooth'
    | '/events/$slug/playlist'
    | '/events/$slug/polls'
    | '/events/$slug/registry'
    | '/events/$slug/replay'
    | '/events/$slug/rsvp'
    | '/events/$slug/seating'
    | '/events/$slug/souvenir'
    | '/events/$slug/speeches'
    | '/events/$slug/thanks'
    | '/events/$slug/timeline'
    | '/events/$slug/toast'
    | '/events/$slug/weather'
    | '/events/$slug/guestbook/new'
    | '/events/$slug/live/setup'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/join'
    | '/legal'
    | '/onboarding'
    | '/app/achievements'
    | '/app/agenda'
    | '/app/care'
    | '/app/community'
    | '/app/create'
    | '/app/explore'
    | '/app/favorites'
    | '/app/gift-ideas'
    | '/app/help'
    | '/app/inspirations'
    | '/app/messages'
    | '/app/notifications'
    | '/app/premium'
    | '/app/profile'
    | '/app/referral'
    | '/app/settings'
    | '/app/story-composer'
    | '/app/vendors'
    | '/app/wallet'
    | '/app/year-in-review'
    | '/events/$slug'
    | '/stories/$slug'
    | '/app/'
    | '/app/messages/$id'
    | '/app/posts/$id'
    | '/app/users/$id'
    | '/app/vendors/$id'
    | '/events/$slug/activity'
    | '/events/$slug/album'
    | '/events/$slug/budget'
    | '/events/$slug/cameras'
    | '/events/$slug/carpool'
    | '/events/$slug/checkin'
    | '/events/$slug/checklist'
    | '/events/$slug/contributors'
    | '/events/$slug/countdown'
    | '/events/$slug/dashboard'
    | '/events/$slug/display'
    | '/events/$slug/dresscode'
    | '/events/$slug/edit'
    | '/events/$slug/faq'
    | '/events/$slug/gifts-received'
    | '/events/$slug/guestbook'
    | '/events/$slug/guests'
    | '/events/$slug/invite'
    | '/events/$slug/kids'
    | '/events/$slug/live'
    | '/events/$slug/live-analytics'
    | '/events/$slug/map'
    | '/events/$slug/moderation'
    | '/events/$slug/photobooth'
    | '/events/$slug/playlist'
    | '/events/$slug/polls'
    | '/events/$slug/registry'
    | '/events/$slug/replay'
    | '/events/$slug/rsvp'
    | '/events/$slug/seating'
    | '/events/$slug/souvenir'
    | '/events/$slug/speeches'
    | '/events/$slug/thanks'
    | '/events/$slug/timeline'
    | '/events/$slug/toast'
    | '/events/$slug/weather'
    | '/events/$slug/guestbook/new'
    | '/events/$slug/live/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  JoinRoute: typeof JoinRoute
  LegalRoute: typeof LegalRoute
  OnboardingRoute: typeof OnboardingRoute
  EventsSlugRoute: typeof EventsSlugRouteWithChildren
  StoriesSlugRoute: typeof StoriesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/stories/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/year-in-review': {
      id: '/app/year-in-review'
      path: '/year-in-review'
      fullPath: '/app/year-in-review'
      preLoaderRoute: typeof AppYearInReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendors': {
      id: '/app/vendors'
      path: '/vendors'
      fullPath: '/app/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/story-composer': {
      id: '/app/story-composer'
      path: '/story-composer'
      fullPath: '/app/story-composer'
      preLoaderRoute: typeof AppStoryComposerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/referral': {
      id: '/app/referral'
      path: '/referral'
      fullPath: '/app/referral'
      preLoaderRoute: typeof AppReferralRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/premium': {
      id: '/app/premium'
      path: '/premium'
      fullPath: '/app/premium'
      preLoaderRoute: typeof AppPremiumRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inspirations': {
      id: '/app/inspirations'
      path: '/inspirations'
      fullPath: '/app/inspirations'
      preLoaderRoute: typeof AppInspirationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gift-ideas': {
      id: '/app/gift-ideas'
      path: '/gift-ideas'
      fullPath: '/app/gift-ideas'
      preLoaderRoute: typeof AppGiftIdeasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/favorites': {
      id: '/app/favorites'
      path: '/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/explore': {
      id: '/app/explore'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/care': {
      id: '/app/care'
      path: '/care'
      fullPath: '/app/care'
      preLoaderRoute: typeof AppCareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/events/$slug/weather': {
      id: '/events/$slug/weather'
      path: '/weather'
      fullPath: '/events/$slug/weather'
      preLoaderRoute: typeof EventsSlugWeatherRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/toast': {
      id: '/events/$slug/toast'
      path: '/toast'
      fullPath: '/events/$slug/toast'
      preLoaderRoute: typeof EventsSlugToastRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/timeline': {
      id: '/events/$slug/timeline'
      path: '/timeline'
      fullPath: '/events/$slug/timeline'
      preLoaderRoute: typeof EventsSlugTimelineRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/thanks': {
      id: '/events/$slug/thanks'
      path: '/thanks'
      fullPath: '/events/$slug/thanks'
      preLoaderRoute: typeof EventsSlugThanksRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/speeches': {
      id: '/events/$slug/speeches'
      path: '/speeches'
      fullPath: '/events/$slug/speeches'
      preLoaderRoute: typeof EventsSlugSpeechesRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/souvenir': {
      id: '/events/$slug/souvenir'
      path: '/souvenir'
      fullPath: '/events/$slug/souvenir'
      preLoaderRoute: typeof EventsSlugSouvenirRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/seating': {
      id: '/events/$slug/seating'
      path: '/seating'
      fullPath: '/events/$slug/seating'
      preLoaderRoute: typeof EventsSlugSeatingRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/rsvp': {
      id: '/events/$slug/rsvp'
      path: '/rsvp'
      fullPath: '/events/$slug/rsvp'
      preLoaderRoute: typeof EventsSlugRsvpRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/replay': {
      id: '/events/$slug/replay'
      path: '/replay'
      fullPath: '/events/$slug/replay'
      preLoaderRoute: typeof EventsSlugReplayRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/registry': {
      id: '/events/$slug/registry'
      path: '/registry'
      fullPath: '/events/$slug/registry'
      preLoaderRoute: typeof EventsSlugRegistryRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/polls': {
      id: '/events/$slug/polls'
      path: '/polls'
      fullPath: '/events/$slug/polls'
      preLoaderRoute: typeof EventsSlugPollsRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/playlist': {
      id: '/events/$slug/playlist'
      path: '/playlist'
      fullPath: '/events/$slug/playlist'
      preLoaderRoute: typeof EventsSlugPlaylistRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/photobooth': {
      id: '/events/$slug/photobooth'
      path: '/photobooth'
      fullPath: '/events/$slug/photobooth'
      preLoaderRoute: typeof EventsSlugPhotoboothRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/moderation': {
      id: '/events/$slug/moderation'
      path: '/moderation'
      fullPath: '/events/$slug/moderation'
      preLoaderRoute: typeof EventsSlugModerationRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/map': {
      id: '/events/$slug/map'
      path: '/map'
      fullPath: '/events/$slug/map'
      preLoaderRoute: typeof EventsSlugMapRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/live-analytics': {
      id: '/events/$slug/live-analytics'
      path: '/live-analytics'
      fullPath: '/events/$slug/live-analytics'
      preLoaderRoute: typeof EventsSlugLiveAnalyticsRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/live': {
      id: '/events/$slug/live'
      path: '/live'
      fullPath: '/events/$slug/live'
      preLoaderRoute: typeof EventsSlugLiveRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/kids': {
      id: '/events/$slug/kids'
      path: '/kids'
      fullPath: '/events/$slug/kids'
      preLoaderRoute: typeof EventsSlugKidsRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/invite': {
      id: '/events/$slug/invite'
      path: '/invite'
      fullPath: '/events/$slug/invite'
      preLoaderRoute: typeof EventsSlugInviteRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/guests': {
      id: '/events/$slug/guests'
      path: '/guests'
      fullPath: '/events/$slug/guests'
      preLoaderRoute: typeof EventsSlugGuestsRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/guestbook': {
      id: '/events/$slug/guestbook'
      path: '/guestbook'
      fullPath: '/events/$slug/guestbook'
      preLoaderRoute: typeof EventsSlugGuestbookRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/gifts-received': {
      id: '/events/$slug/gifts-received'
      path: '/gifts-received'
      fullPath: '/events/$slug/gifts-received'
      preLoaderRoute: typeof EventsSlugGiftsReceivedRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/faq': {
      id: '/events/$slug/faq'
      path: '/faq'
      fullPath: '/events/$slug/faq'
      preLoaderRoute: typeof EventsSlugFaqRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/edit': {
      id: '/events/$slug/edit'
      path: '/edit'
      fullPath: '/events/$slug/edit'
      preLoaderRoute: typeof EventsSlugEditRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/dresscode': {
      id: '/events/$slug/dresscode'
      path: '/dresscode'
      fullPath: '/events/$slug/dresscode'
      preLoaderRoute: typeof EventsSlugDresscodeRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/display': {
      id: '/events/$slug/display'
      path: '/display'
      fullPath: '/events/$slug/display'
      preLoaderRoute: typeof EventsSlugDisplayRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/dashboard': {
      id: '/events/$slug/dashboard'
      path: '/dashboard'
      fullPath: '/events/$slug/dashboard'
      preLoaderRoute: typeof EventsSlugDashboardRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/countdown': {
      id: '/events/$slug/countdown'
      path: '/countdown'
      fullPath: '/events/$slug/countdown'
      preLoaderRoute: typeof EventsSlugCountdownRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/contributors': {
      id: '/events/$slug/contributors'
      path: '/contributors'
      fullPath: '/events/$slug/contributors'
      preLoaderRoute: typeof EventsSlugContributorsRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/checklist': {
      id: '/events/$slug/checklist'
      path: '/checklist'
      fullPath: '/events/$slug/checklist'
      preLoaderRoute: typeof EventsSlugChecklistRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/checkin': {
      id: '/events/$slug/checkin'
      path: '/checkin'
      fullPath: '/events/$slug/checkin'
      preLoaderRoute: typeof EventsSlugCheckinRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/carpool': {
      id: '/events/$slug/carpool'
      path: '/carpool'
      fullPath: '/events/$slug/carpool'
      preLoaderRoute: typeof EventsSlugCarpoolRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/cameras': {
      id: '/events/$slug/cameras'
      path: '/cameras'
      fullPath: '/events/$slug/cameras'
      preLoaderRoute: typeof EventsSlugCamerasRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/budget': {
      id: '/events/$slug/budget'
      path: '/budget'
      fullPath: '/events/$slug/budget'
      preLoaderRoute: typeof EventsSlugBudgetRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/album': {
      id: '/events/$slug/album'
      path: '/album'
      fullPath: '/events/$slug/album'
      preLoaderRoute: typeof EventsSlugAlbumRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/activity': {
      id: '/events/$slug/activity'
      path: '/activity'
      fullPath: '/events/$slug/activity'
      preLoaderRoute: typeof EventsSlugActivityRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/app/vendors/$id': {
      id: '/app/vendors/$id'
      path: '/$id'
      fullPath: '/app/vendors/$id'
      preLoaderRoute: typeof AppVendorsIdRouteImport
      parentRoute: typeof AppVendorsRoute
    }
    '/app/users/$id': {
      id: '/app/users/$id'
      path: '/users/$id'
      fullPath: '/app/users/$id'
      preLoaderRoute: typeof AppUsersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/posts/$id': {
      id: '/app/posts/$id'
      path: '/posts/$id'
      fullPath: '/app/posts/$id'
      preLoaderRoute: typeof AppPostsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages/$id': {
      id: '/app/messages/$id'
      path: '/$id'
      fullPath: '/app/messages/$id'
      preLoaderRoute: typeof AppMessagesIdRouteImport
      parentRoute: typeof AppMessagesRoute
    }
    '/events/$slug/live/setup': {
      id: '/events/$slug/live/setup'
      path: '/setup'
      fullPath: '/events/$slug/live/setup'
      preLoaderRoute: typeof EventsSlugLiveSetupRouteImport
      parentRoute: typeof EventsSlugLiveRoute
    }
    '/events/$slug/guestbook/new': {
      id: '/events/$slug/guestbook/new'
      path: '/new'
      fullPath: '/events/$slug/guestbook/new'
      preLoaderRoute: typeof EventsSlugGuestbookNewRouteImport
      parentRoute: typeof EventsSlugGuestbookRoute
    }
  }
}

interface AppMessagesRouteChildren {
  AppMessagesIdRoute: typeof AppMessagesIdRoute
}

const AppMessagesRouteChildren: AppMessagesRouteChildren = {
  AppMessagesIdRoute: AppMessagesIdRoute,
}

const AppMessagesRouteWithChildren = AppMessagesRoute._addFileChildren(
  AppMessagesRouteChildren,
)

interface AppVendorsRouteChildren {
  AppVendorsIdRoute: typeof AppVendorsIdRoute
}

const AppVendorsRouteChildren: AppVendorsRouteChildren = {
  AppVendorsIdRoute: AppVendorsIdRoute,
}

const AppVendorsRouteWithChildren = AppVendorsRoute._addFileChildren(
  AppVendorsRouteChildren,
)

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppAgendaRoute: typeof AppAgendaRoute
  AppCareRoute: typeof AppCareRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppCreateRoute: typeof AppCreateRoute
  AppExploreRoute: typeof AppExploreRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppGiftIdeasRoute: typeof AppGiftIdeasRoute
  AppHelpRoute: typeof AppHelpRoute
  AppInspirationsRoute: typeof AppInspirationsRoute
  AppMessagesRoute: typeof AppMessagesRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPremiumRoute: typeof AppPremiumRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReferralRoute: typeof AppReferralRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStoryComposerRoute: typeof AppStoryComposerRoute
  AppVendorsRoute: typeof AppVendorsRouteWithChildren
  AppWalletRoute: typeof AppWalletRoute
  AppYearInReviewRoute: typeof AppYearInReviewRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPostsIdRoute: typeof AppPostsIdRoute
  AppUsersIdRoute: typeof AppUsersIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppAgendaRoute: AppAgendaRoute,
  AppCareRoute: AppCareRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppCreateRoute: AppCreateRoute,
  AppExploreRoute: AppExploreRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppGiftIdeasRoute: AppGiftIdeasRoute,
  AppHelpRoute: AppHelpRoute,
  AppInspirationsRoute: AppInspirationsRoute,
  AppMessagesRoute: AppMessagesRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPremiumRoute: AppPremiumRoute,
  AppProfileRoute: AppProfileRoute,
  AppReferralRoute: AppReferralRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStoryComposerRoute: AppStoryComposerRoute,
  AppVendorsRoute: AppVendorsRouteWithChildren,
  AppWalletRoute: AppWalletRoute,
  AppYearInReviewRoute: AppYearInReviewRoute,
  AppIndexRoute: AppIndexRoute,
  AppPostsIdRoute: AppPostsIdRoute,
  AppUsersIdRoute: AppUsersIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface EventsSlugGuestbookRouteChildren {
  EventsSlugGuestbookNewRoute: typeof EventsSlugGuestbookNewRoute
}

const EventsSlugGuestbookRouteChildren: EventsSlugGuestbookRouteChildren = {
  EventsSlugGuestbookNewRoute: EventsSlugGuestbookNewRoute,
}

const EventsSlugGuestbookRouteWithChildren =
  EventsSlugGuestbookRoute._addFileChildren(EventsSlugGuestbookRouteChildren)

interface EventsSlugLiveRouteChildren {
  EventsSlugLiveSetupRoute: typeof EventsSlugLiveSetupRoute
}

const EventsSlugLiveRouteChildren: EventsSlugLiveRouteChildren = {
  EventsSlugLiveSetupRoute: EventsSlugLiveSetupRoute,
}

const EventsSlugLiveRouteWithChildren = EventsSlugLiveRoute._addFileChildren(
  EventsSlugLiveRouteChildren,
)

interface EventsSlugRouteChildren {
  EventsSlugActivityRoute: typeof EventsSlugActivityRoute
  EventsSlugAlbumRoute: typeof EventsSlugAlbumRoute
  EventsSlugBudgetRoute: typeof EventsSlugBudgetRoute
  EventsSlugCamerasRoute: typeof EventsSlugCamerasRoute
  EventsSlugCarpoolRoute: typeof EventsSlugCarpoolRoute
  EventsSlugCheckinRoute: typeof EventsSlugCheckinRoute
  EventsSlugChecklistRoute: typeof EventsSlugChecklistRoute
  EventsSlugContributorsRoute: typeof EventsSlugContributorsRoute
  EventsSlugCountdownRoute: typeof EventsSlugCountdownRoute
  EventsSlugDashboardRoute: typeof EventsSlugDashboardRoute
  EventsSlugDisplayRoute: typeof EventsSlugDisplayRoute
  EventsSlugDresscodeRoute: typeof EventsSlugDresscodeRoute
  EventsSlugEditRoute: typeof EventsSlugEditRoute
  EventsSlugFaqRoute: typeof EventsSlugFaqRoute
  EventsSlugGiftsReceivedRoute: typeof EventsSlugGiftsReceivedRoute
  EventsSlugGuestbookRoute: typeof EventsSlugGuestbookRouteWithChildren
  EventsSlugGuestsRoute: typeof EventsSlugGuestsRoute
  EventsSlugInviteRoute: typeof EventsSlugInviteRoute
  EventsSlugKidsRoute: typeof EventsSlugKidsRoute
  EventsSlugLiveRoute: typeof EventsSlugLiveRouteWithChildren
  EventsSlugLiveAnalyticsRoute: typeof EventsSlugLiveAnalyticsRoute
  EventsSlugMapRoute: typeof EventsSlugMapRoute
  EventsSlugModerationRoute: typeof EventsSlugModerationRoute
  EventsSlugPhotoboothRoute: typeof EventsSlugPhotoboothRoute
  EventsSlugPlaylistRoute: typeof EventsSlugPlaylistRoute
  EventsSlugPollsRoute: typeof EventsSlugPollsRoute
  EventsSlugRegistryRoute: typeof EventsSlugRegistryRoute
  EventsSlugReplayRoute: typeof EventsSlugReplayRoute
  EventsSlugRsvpRoute: typeof EventsSlugRsvpRoute
  EventsSlugSeatingRoute: typeof EventsSlugSeatingRoute
  EventsSlugSouvenirRoute: typeof EventsSlugSouvenirRoute
  EventsSlugSpeechesRoute: typeof EventsSlugSpeechesRoute
  EventsSlugThanksRoute: typeof EventsSlugThanksRoute
  EventsSlugTimelineRoute: typeof EventsSlugTimelineRoute
  EventsSlugToastRoute: typeof EventsSlugToastRoute
  EventsSlugWeatherRoute: typeof EventsSlugWeatherRoute
}

const EventsSlugRouteChildren: EventsSlugRouteChildren = {
  EventsSlugActivityRoute: EventsSlugActivityRoute,
  EventsSlugAlbumRoute: EventsSlugAlbumRoute,
  EventsSlugBudgetRoute: EventsSlugBudgetRoute,
  EventsSlugCamerasRoute: EventsSlugCamerasRoute,
  EventsSlugCarpoolRoute: EventsSlugCarpoolRoute,
  EventsSlugCheckinRoute: EventsSlugCheckinRoute,
  EventsSlugChecklistRoute: EventsSlugChecklistRoute,
  EventsSlugContributorsRoute: EventsSlugContributorsRoute,
  EventsSlugCountdownRoute: EventsSlugCountdownRoute,
  EventsSlugDashboardRoute: EventsSlugDashboardRoute,
  EventsSlugDisplayRoute: EventsSlugDisplayRoute,
  EventsSlugDresscodeRoute: EventsSlugDresscodeRoute,
  EventsSlugEditRoute: EventsSlugEditRoute,
  EventsSlugFaqRoute: EventsSlugFaqRoute,
  EventsSlugGiftsReceivedRoute: EventsSlugGiftsReceivedRoute,
  EventsSlugGuestbookRoute: EventsSlugGuestbookRouteWithChildren,
  EventsSlugGuestsRoute: EventsSlugGuestsRoute,
  EventsSlugInviteRoute: EventsSlugInviteRoute,
  EventsSlugKidsRoute: EventsSlugKidsRoute,
  EventsSlugLiveRoute: EventsSlugLiveRouteWithChildren,
  EventsSlugLiveAnalyticsRoute: EventsSlugLiveAnalyticsRoute,
  EventsSlugMapRoute: EventsSlugMapRoute,
  EventsSlugModerationRoute: EventsSlugModerationRoute,
  EventsSlugPhotoboothRoute: EventsSlugPhotoboothRoute,
  EventsSlugPlaylistRoute: EventsSlugPlaylistRoute,
  EventsSlugPollsRoute: EventsSlugPollsRoute,
  EventsSlugRegistryRoute: EventsSlugRegistryRoute,
  EventsSlugReplayRoute: EventsSlugReplayRoute,
  EventsSlugRsvpRoute: EventsSlugRsvpRoute,
  EventsSlugSeatingRoute: EventsSlugSeatingRoute,
  EventsSlugSouvenirRoute: EventsSlugSouvenirRoute,
  EventsSlugSpeechesRoute: EventsSlugSpeechesRoute,
  EventsSlugThanksRoute: EventsSlugThanksRoute,
  EventsSlugTimelineRoute: EventsSlugTimelineRoute,
  EventsSlugToastRoute: EventsSlugToastRoute,
  EventsSlugWeatherRoute: EventsSlugWeatherRoute,
}

const EventsSlugRouteWithChildren = EventsSlugRoute._addFileChildren(
  EventsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  JoinRoute: JoinRoute,
  LegalRoute: LegalRoute,
  OnboardingRoute: OnboardingRoute,
  EventsSlugRoute: EventsSlugRouteWithChildren,
  StoriesSlugRoute: StoriesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
