/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppFavoritesRouteImport } from './routes/app.favorites'
import { Route as AppExploreRouteImport } from './routes/app.explore'
import { Route as AppCreateRouteImport } from './routes/app.create'
import { Route as EventsSlugLiveRouteImport } from './routes/events.$slug.live'
import { Route as EventsSlugInviteRouteImport } from './routes/events.$slug.invite'
import { Route as EventsSlugGuestsRouteImport } from './routes/events.$slug.guests'
import { Route as EventsSlugGuestbookRouteImport } from './routes/events.$slug.guestbook'
import { Route as EventsSlugAlbumRouteImport } from './routes/events.$slug.album'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/stories/$slug',
  path: '/stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const EventsSlugLiveRoute = EventsSlugLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugInviteRoute = EventsSlugInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugGuestsRoute = EventsSlugGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugGuestbookRoute = EventsSlugGuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugAlbumRoute = EventsSlugAlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => EventsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/app/create': typeof AppCreateRoute
  '/app/explore': typeof AppExploreRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/stories/$slug': typeof StoriesSlugRoute
  '/app/': typeof AppIndexRoute
  '/events/$slug/album': typeof EventsSlugAlbumRoute
  '/events/$slug/guestbook': typeof EventsSlugGuestbookRoute
  '/events/$slug/guests': typeof EventsSlugGuestsRoute
  '/events/$slug/invite': typeof EventsSlugInviteRoute
  '/events/$slug/live': typeof EventsSlugLiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/app/create': typeof AppCreateRoute
  '/app/explore': typeof AppExploreRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/stories/$slug': typeof StoriesSlugRoute
  '/app': typeof AppIndexRoute
  '/events/$slug/album': typeof EventsSlugAlbumRoute
  '/events/$slug/guestbook': typeof EventsSlugGuestbookRoute
  '/events/$slug/guests': typeof EventsSlugGuestsRoute
  '/events/$slug/invite': typeof EventsSlugInviteRoute
  '/events/$slug/live': typeof EventsSlugLiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/app/create': typeof AppCreateRoute
  '/app/explore': typeof AppExploreRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/stories/$slug': typeof StoriesSlugRoute
  '/app/': typeof AppIndexRoute
  '/events/$slug/album': typeof EventsSlugAlbumRoute
  '/events/$slug/guestbook': typeof EventsSlugGuestbookRoute
  '/events/$slug/guests': typeof EventsSlugGuestsRoute
  '/events/$slug/invite': typeof EventsSlugInviteRoute
  '/events/$slug/live': typeof EventsSlugLiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/join'
    | '/app/create'
    | '/app/explore'
    | '/app/favorites'
    | '/app/messages'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/events/$slug'
    | '/stories/$slug'
    | '/app/'
    | '/events/$slug/album'
    | '/events/$slug/guestbook'
    | '/events/$slug/guests'
    | '/events/$slug/invite'
    | '/events/$slug/live'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/join'
    | '/app/create'
    | '/app/explore'
    | '/app/favorites'
    | '/app/messages'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/events/$slug'
    | '/stories/$slug'
    | '/app'
    | '/events/$slug/album'
    | '/events/$slug/guestbook'
    | '/events/$slug/guests'
    | '/events/$slug/invite'
    | '/events/$slug/live'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/join'
    | '/app/create'
    | '/app/explore'
    | '/app/favorites'
    | '/app/messages'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/events/$slug'
    | '/stories/$slug'
    | '/app/'
    | '/events/$slug/album'
    | '/events/$slug/guestbook'
    | '/events/$slug/guests'
    | '/events/$slug/invite'
    | '/events/$slug/live'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  JoinRoute: typeof JoinRoute
  EventsSlugRoute: typeof EventsSlugRouteWithChildren
  StoriesSlugRoute: typeof StoriesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/stories/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/favorites': {
      id: '/app/favorites'
      path: '/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/explore': {
      id: '/app/explore'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/events/$slug/live': {
      id: '/events/$slug/live'
      path: '/live'
      fullPath: '/events/$slug/live'
      preLoaderRoute: typeof EventsSlugLiveRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/invite': {
      id: '/events/$slug/invite'
      path: '/invite'
      fullPath: '/events/$slug/invite'
      preLoaderRoute: typeof EventsSlugInviteRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/guests': {
      id: '/events/$slug/guests'
      path: '/guests'
      fullPath: '/events/$slug/guests'
      preLoaderRoute: typeof EventsSlugGuestsRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/guestbook': {
      id: '/events/$slug/guestbook'
      path: '/guestbook'
      fullPath: '/events/$slug/guestbook'
      preLoaderRoute: typeof EventsSlugGuestbookRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/album': {
      id: '/events/$slug/album'
      path: '/album'
      fullPath: '/events/$slug/album'
      preLoaderRoute: typeof EventsSlugAlbumRouteImport
      parentRoute: typeof EventsSlugRoute
    }
  }
}

interface AppRouteChildren {
  AppCreateRoute: typeof AppCreateRoute
  AppExploreRoute: typeof AppExploreRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateRoute: AppCreateRoute,
  AppExploreRoute: AppExploreRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface EventsSlugRouteChildren {
  EventsSlugAlbumRoute: typeof EventsSlugAlbumRoute
  EventsSlugGuestbookRoute: typeof EventsSlugGuestbookRoute
  EventsSlugGuestsRoute: typeof EventsSlugGuestsRoute
  EventsSlugInviteRoute: typeof EventsSlugInviteRoute
  EventsSlugLiveRoute: typeof EventsSlugLiveRoute
}

const EventsSlugRouteChildren: EventsSlugRouteChildren = {
  EventsSlugAlbumRoute: EventsSlugAlbumRoute,
  EventsSlugGuestbookRoute: EventsSlugGuestbookRoute,
  EventsSlugGuestsRoute: EventsSlugGuestsRoute,
  EventsSlugInviteRoute: EventsSlugInviteRoute,
  EventsSlugLiveRoute: EventsSlugLiveRoute,
}

const EventsSlugRouteWithChildren = EventsSlugRoute._addFileChildren(
  EventsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  JoinRoute: JoinRoute,
  EventsSlugRoute: EventsSlugRouteWithChildren,
  StoriesSlugRoute: StoriesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
